# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef5bc89f87dfddfe5ffa0be933ec018bce4f39b26bbf9f51bb830b8e6dc6cb92e3828253cf09b36243aed8750e7503f67c54314923677e12b64a15ed01bc5342

test:
  secret_key_base: 5180db44f3a31c356dbe531f033901f97a4e116e445ece39c30087dde620797d4153c89e76df4618563a4b52b033b971075e853fe85bf786f269f446418ab55b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
